# Generated by Django 4.0 on 2022-04-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_holdername', models.CharField(max_length=50)),
                ('bank_ifsc', models.CharField(max_length=30)),
                ('bank_accountname', models.CharField(max_length=30)),
                ('bank_branch', models.CharField(max_length=30)),
                ('bank_balance', models.IntegerField()),
            ],
            options={
                'db_table': 'addbank',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_gst_number', models.CharField(max_length=30)),
                ('client_id', models.CharField(default=0, max_length=30)),
                ('client_phone', models.CharField(max_length=30)),
                ('client_email', models.CharField(max_length=30)),
                ('client_state', models.CharField(max_length=30)),
                ('client_district', models.CharField(max_length=30)),
                ('client_zipcode', models.CharField(max_length=30)),
                ('client_address', models.CharField(max_length=60)),
                ('client_whsatpp', models.CharField(max_length=60)),
                ('client_contact_type', models.CharField(default='', max_length=40)),
                ('client_status', models.CharField(default='Active', max_length=30)),
                ('client_bankholder', models.CharField(default='', max_length=60)),
                ('client_bankname', models.CharField(default='', max_length=60)),
                ('client_ifsc', models.CharField(default='', max_length=60)),
                ('client_actnnumber', models.CharField(default='', max_length=60)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_username', models.CharField(max_length=50)),
                ('employee_password', models.CharField(max_length=50)),
                ('employee_phone', models.CharField(max_length=30)),
                ('employee_email', models.CharField(max_length=30)),
                ('employee_state', models.CharField(max_length=30)),
                ('employee_district', models.CharField(max_length=30)),
                ('employee_zipcode', models.CharField(max_length=30)),
                ('employee_address', models.CharField(max_length=30)),
                ('employee_status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('catagory', models.CharField(max_length=50)),
                ('priceper_head', models.IntegerField()),
                ('priceper_kg', models.IntegerField()),
                ('food_deatails', models.CharField(max_length=50)),
                ('food_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_fromdate', models.CharField(max_length=50)),
                ('est_todate', models.CharField(max_length=50)),
                ('est_id', models.CharField(max_length=50)),
                ('clientlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.client')),
            ],
        ),
    ]
