# Generated by Django 4.0.4 on 2022-04-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estimates',
            table=None,
        ),
    ]
