# Generated by Django 4.0 on 2022-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
