# Generated by Django 4.0.4 on 2022-04-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('catagory', models.CharField(max_length=50)),
                ('priceper_head', models.CharField(max_length=50)),
                ('priceper_kg', models.CharField(max_length=50)),
                ('food_deatails', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
