# Generated by Django 4.0 on 2022-04-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_employee_employee_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
