# Generated by Django 4.0 on 2022-04-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_productname', models.CharField(max_length=50)),
                ('est_category', models.CharField(max_length=50)),
                ('est_amount', models.CharField(max_length=50)),
                ('est_qty', models.CharField(max_length=50)),
                ('est_price', models.CharField(max_length=50)),
                ('estimate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.estimate')),
            ],
        ),
    ]
