# Generated by Django 4.0 on 2022-04-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_employee_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='addbank',
            table='addBank',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
