# Generated by Django 4.0 on 2022-04-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_estimateproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateproduct',
            name='est_productname',
        ),
    ]
