# Generated by Django 4.0 on 2022-04-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_estimateproduct_est_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='est_id',
        ),
    ]
