# Generated by Django 4.0.4 on 2022-04-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_addbank_table_alter_client_table_and_more'),
        ('adminapp', '0004_employee_employee_status_alter_addbank_table_and_more'),
    ]

    operations = [
    ]
