# Generated by Django 4.0 on 2022-04-26 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_estimate_est_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_fromdate', models.CharField(max_length=50)),
                ('est_todate', models.CharField(max_length=50)),
                ('clientd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.client')),
            ],
            options={
                'db_table': 'estimates',
            },
        ),
        migrations.AlterField(
            model_name='estimateproduct',
            name='estimate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.estimates'),
        ),
        migrations.DeleteModel(
            name='Estimate',
        ),
    ]
