# Generated by Django 4.0 on 2022-04-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_merge_20220422_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbank',
            name='bank_branch',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
