# Generated by Django 4.0.4 on 2022-04-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_merge_20220422_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
        migrations.AddField(
            model_name='client',
            name='client_gst',
            field=models.CharField(default='', max_length=20),
        ),
    ]
