# Generated by Django 4.0.4 on 2022-04-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_client_client_id_client_client_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_gst',
        ),
    ]
