# Generated by Django 4.0 on 2022-04-27 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_estimates_alter_estimateproduct_estimate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateproduct',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.product'),
            preserve_default=False,
        ),
    ]
