# Generated by Django 4.0 on 2022-04-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_estimateproduct_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimateproduct',
            old_name='estimate_id',
            new_name='estimateid',
        ),
        migrations.RenameField(
            model_name='estimateproduct',
            old_name='product_id',
            new_name='productid',
        ),
    ]
