# Generated by Django 4.0.4 on 2022-04-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_client_client_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_contact_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
