# Generated by Django 4.0.4 on 2022-04-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_client_client_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='client_status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
