# Generated by Django 4.0 on 2022-04-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_addbank_bank_branch'),
        ('adminapp', '0010_alter_client_client_address_and_more'),
    ]

    operations = [
    ]
