# Generated by Django 4.0 on 2022-04-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_merge_20220423_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_whsatpp',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.BooleanField(default=False),
        ),
    ]
