# Generated by Django 4.0 on 2022-04-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_client_client_whsatpp_alter_client_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_actnnumber',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='client',
            name='client_bankholder',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='client',
            name='client_bankname',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='client',
            name='client_ifsc',
            field=models.CharField(default='', max_length=60),
        ),
    ]
