# Generated by Django 4.0 on 2022-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_client_client_actnnumber_client_client_bankholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_status',
            field=models.BooleanField(default=True),
        ),
    ]
