# Generated by Django 4.0 on 2022-04-25 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_alter_client_client_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_fromdate', models.CharField(max_length=50)),
                ('est_todate', models.CharField(max_length=50)),
                ('est_id', models.CharField(max_length=50)),
                ('clientlogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.client')),
            ],
        ),
    ]
